spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipes
    username: bob
    password: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
recipes:
  openapi:
    dev-url: http://localhost:8080
    prod-url: https://bezkoder-api.com